# Generated by Django 4.2.2 on 2023-06-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
