# Generated by Django 4.2.2 on 2023-06-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_delete_project_book_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Develop',
        ),
    ]
