# Generated by Django 4.2.2 on 2023-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_develop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexInfo', models.TextField()),
            ],
        ),
    ]
