# Generated by Django 4.2.2 on 2023-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_section_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='image_file',
            field=models.FileField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
