# Generated by Django 4.2.2 on 2023-06-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_remove_card_image_card_image_file_card_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Project',
        ),
        migrations.DeleteModel(
            name='Develop',
        ),
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='card',
            name='author',
        ),
        migrations.RemoveField(
            model_name='card',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='section',
        ),
        migrations.AlterField(
            model_name='card',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.developer'),
            preserve_default=False,
        ),
    ]
