# Generated by Django 4.2.2 on 2023-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_developer_rename_section_project_delete_develop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя разрабочика'),
        ),
    ]
