# Generated by Django 4.2.2 on 2023-06-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_manager_viewonlypermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('can_view_all', 'Может только просматривать все модели')]},
        ),
    ]
