# Generated by Django 4.2.2 on 2023-06-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
